--- #YAML:1.0
name:                Pod-InDesign-TaggedText-TPR
version:             0.10
abstract:            Convert Pod to InDesign's Tagged Text format for The Perl Review
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Pod::Escapes:                  0
    Pod::InDesign::TaggedText:     0
    Pod::Simple:                   0
    Test::LongString:              0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
